import { Link } from "wouter";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronRight, Leaf, LockKeyhole, Sprout, Store, SunMedium } from "lucide-react";
import { Brand } from "@/components/FarmUI";
import { useAuth } from "@/contexts/AuthContext";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";

const fieldHero = "/manus-storage/farmai-field-hero-source_bf3abcf8.jpeg";
export default function Home() {
  const { user, role } = useAuth();
  return <div className="landing-page">
    <header className="landing-nav"><Brand /><nav><a href="#how-it-works">How it works</a><a href="#for-growers">For growers</a><a href="#market">For buyers</a></nav><div className="landing-nav-actions"><LanguageSwitcher compact />{user ? <Link className="landing-signin" href={role === "buyer" ? "/buyer" : "/farmer"}>Open your workspace <ArrowUpRight size={15} /></Link> : <><Link className="landing-signin" href="/login">Sign in</Link><Link className="landing-cta" href="/register/farmer">Get started <ArrowRight size={15} /></Link></>}</div></header>
    <main>
      <section className="landing-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(20,43,31,.91) 0%, rgba(20,43,31,.75) 42%, rgba(20,43,31,.08) 100%), url('${fieldHero}')` }}><div className="hero-grain" /><div className="landing-hero-content"><div className="hero-kicker"><span className="hero-kicker-line" /> THE FARM, IN FOCUS</div><h1>Grow with<br /><em>more clarity.</em></h1><p>One calm workspace for your farm records, crop journeys and the people who bring produce to market.</p><div className="landing-hero-actions"><Link className="hero-primary-button" href="/register/farmer">Start as a farmer <ArrowRight size={16} /></Link><Link className="hero-secondary-button" href="/register/buyer">I'm a produce buyer <ArrowUpRight size={15} /></Link></div><div className="hero-footnote"><LockKeyhole size={13} /> Your data. Your decisions. No invented forecasts.</div></div><div className="hero-image-caption"><span>FIELD NOTES</span><span>001 / A PLACE TO BEGIN</span></div><a className="hero-scroll" href="#how-it-works"><span>SCROLL TO EXPLORE</span><ArrowDown size={14} /></a></section>
      <section id="how-it-works" className="landing-intro"><div className="landing-section-label">A MORE GROUNDED WAY TO GROW <span>01 — 03</span></div><div className="intro-grid"><h2>A season isn't<br />just a <em>spreadsheet.</em></h2><div className="intro-copy"><p>It's soil under your nails, a task you almost forgot, the first green at the edge of a field. FarmSaathi brings your everyday farm notes into one connected view — and stays honest about what it knows.</p><a href="#for-growers" className="text-link">See what's possible <ArrowRight size={15} /></a></div></div><div className="intro-statement"><Sprout size={21} /><span>Start with what you know. Build a clearer picture as you go.</span></div></section>
      <section id="for-growers" className="landing-features"><div className="landing-feature-heading"><div><div className="eyebrow">FOR THE PEOPLE WHO GROW</div><h2>Your farm,<br /><em>all in one place.</em></h2></div><p>Less searching through notes. More continuity from one season to the next.</p></div><div className="feature-grid"><article className="feature-card feature-big"><span className="feature-number">01 / FIELD NOTES</span><span className="feature-icon"><Leaf size={21} /></span><h3>Know each piece<br />of your land.</h3><p>Organize farms, fields, soil observations and multiple crop journeys with their own records.</p><div className="feature-illustration landscape"><div className="land-row row-a" /><div className="land-row row-b" /><div className="land-row row-c" /><Sprout size={51} /></div></article><article className="feature-card"><span className="feature-number">02 / THE SEASON</span><span className="feature-icon feature-icon-earth"><SunMedium size={21} /></span><h3>Keep the small<br />things connected.</h3><p>Tasks, watering, inputs, costs and harvests connected to the crop they belong to.</p><div className="feature-footer"><Check size={15} /> Your records, together</div></article><article id="market" className="feature-card feature-market"><span className="feature-number">03 / A FAIRER MARKET</span><span className="feature-icon feature-icon-gold"><Store size={21} /></span><h3>Bring a harvest<br />to market.</h3><p>Post an offer from a saved harvest. Explore produce posted by growers.</p><Link className="feature-footer feature-market-link" href="/register/buyer">Explore for buyers <ArrowRight size={15} /></Link></article></div></section>
      <section className="landing-ai-section"><div className="ai-section-art"><div className="ai-art-ring ring-one" /><div className="ai-art-ring ring-two" /><div className="ai-art-center"><Sprout size={35} /></div><span className="ai-star star-a" /><span className="ai-star star-b" /><span className="ai-star star-c" /></div><div className="ai-section-copy"><div className="eyebrow">HELPFUL, NOT ALL-KNOWING</div><h2>Ask a question.<br /><em>Keep the judgment.</em></h2><p>FarmSaathi can use the context you share to help with your records. It won't diagnose a plant with certainty, invent local prices or make changes without your confirmation.</p><Link href="/register/farmer" className="text-link">Meet FarmSaathi <ArrowRight size={15} /></Link></div></section>
      <section className="landing-audience"><div className="landing-section-label">TWO SIDES OF A GOOD HARVEST <span>02 — 03</span></div><div className="audience-grid"><article className="audience-card grower-audience"><div className="audience-number">01</div><div className="eyebrow">FOR FARMERS</div><h3>A workspace for<br />your growing season.</h3><p>Bring farm records together, keep a crop journey, record a harvest and manage your produce offers.</p><Link href="/register/farmer" className="audience-link">Build your farm workspace <ArrowRight size={16} /></Link><span className="audience-watermark"><Leaf size={104} /></span></article><article className="audience-card buyer-audience"><div className="audience-number">02</div><div className="eyebrow">FOR PRODUCE BUYERS</div><h3>Source with<br />more context.</h3><p>Browse active offers, share the qualities you need and manage interest with growers.</p><Link href="/register/buyer" className="audience-link">Explore the marketplace <ArrowRight size={16} /></Link><span className="audience-watermark"><Store size={100} /></span></article></div></section>
      <section className="landing-cta-section"><div className="cta-orbit"><div className="cta-orbit-ring" /><Sprout size={32} /></div><div className="eyebrow">A CLEARER NEXT STEP</div><h2>Make room for<br /><em>what's growing.</em></h2><p>Start a workspace that's grounded in your records, and grows alongside your season.</p><div className="landing-hero-actions"><Link className="hero-primary-button" href="/register/farmer">Create your workspace <ArrowRight size={16} /></Link><Link className="hero-secondary-button light" href="/register/buyer">Join as a buyer <ChevronRight size={16} /></Link></div></section>
    </main>
    <footer className="landing-footer"><Brand /><span>© {new Date().getFullYear()} FarmSaathi. Made for the hands that grow.</span><div><Link href="/login">Sign in</Link><Link href="/help">Help</Link></div></footer>
  </div>;
}
