import { useMemo, useState, type FormEvent } from "react";
import { Link, useLocation } from "wouter";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Check, Clock3, FileImage, LoaderCircle, MapPin, Package, Plus, Search, ShieldCheck, Sprout, Store, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { api, errorMessage, recordId, type IdRecord, type Listing } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import { qk, useListings } from "@/hooks/useFarmData";
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState, PageHeading, PageSurface, SectionHeading, SelectInput, TextArea, TextInput } from "@/components/FarmUI";
import { formatDate, formatNumber } from "@/lib/locale";

const pretty = (value: unknown) => String(value ?? "Not recorded").replaceAll("_", " ").replace(/\b\w/g, char => char.toUpperCase());
const dateText = (value: unknown) => value ? formatDate(String(value), { day: "numeric", month: "short", year: "numeric" }) : "No date set";
const formatPrice = (currency: unknown, price: unknown) => `${String(currency || "INR")} ${formatNumber(Number(price || 0))}`;
const farmerPath = (path: string) => `/farmer/${path}`;
const buyerPath = (path: string) => `/buyer/${path}`;

export function MarketPage({ sellerView = false }: { sellerView?: boolean }) {
  const { user, role } = useAuth(); const [query, setQuery] = useState(""); const [crop, setCrop] = useState(""); const [sort, setSort] = useState("newest");
  const params = useMemo(() => ({ q: query.trim() || undefined, crop: crop.trim() || undefined, sort, limit: 24, offset: 0 }), [query, crop, sort]);
  const listings = useListings(params); const prices = useQuery({ queryKey: ["market-prices", crop], queryFn: () => api.support.marketPrices(crop || undefined) });
  const mine = (listings.data?.items || []).filter(item => { const seller = item.seller as Record<string, unknown> | undefined; return String(seller?._id || seller?.id || "") === String(user?._id || user?.id || ""); });
  const viewItems = sellerView ? mine : listings.data?.items || [];
  const isFarmer = role === "farmer";
  return <PageSurface><PageHeading eyebrow={sellerView ? "YOUR PRODUCE" : isFarmer ? "MARKET CONTEXT" : "FARMSAATHI MARKET"} title={sellerView ? "Offers from your farm." : isFarmer ? "See what the market says." : "Good produce starts here."} subtitle={sellerView ? "Manage active produce listings created from your harvest records." : isFarmer ? "Browse active produce offers and check connected market-price availability." : "Browse grower listings. Exact farm coordinates are never displayed."} action={isFarmer ? <Link href={farmerPath("listings/new")} className="button button-primary"><Plus size={16} /> Create listing</Link> : <Link href={buyerPath("requirements/new")} className="button button-primary"><Plus size={16} /> Post a requirement</Link>} />
    {!sellerView && <Card className="market-price-bar"><div className="price-bar-icon"><Store size={18} /></div><div className="price-bar-copy"><strong>Market prices</strong><span>{prices.data?.available ? `Latest data from ${prices.data.source || "configured provider"}.` : prices.data?.reason || (prices.isLoading ? "Checking configured price source…" : "No price provider is available right now.")}</span></div><Link href={`/${role}/market/prices`} className="inline-link">Market prices <ArrowRight size={14} /></Link></Card>}
    {!sellerView && <div className="market-search-panel"><div className="market-search-icon"><Search size={19} /></div><div className="market-search-fields"><label htmlFor="market-q" className="sr-only">Search crops and varieties</label><input id="market-q" className="market-search-input" placeholder="Search a crop or variety…" value={query} onChange={event => setQuery(event.target.value)} /><div className="market-search-divider" /><label htmlFor="market-sort" className="sr-only">Sort listings</label><select id="market-sort" className="market-sort-select" value={sort} onChange={event => setSort(event.target.value)}><option value="newest">Newest first</option><option value="price_asc">Lowest price</option><option value="price_desc">Highest price</option></select></div><span className="market-live-tag"><span /> LIVE LISTINGS</span></div>}
    {sellerView && <div className="market-seller-note"><Package size={17} /><span>Your listing quantity is reserved from its linked harvest, and is restored if a listing closes without active transactions.</span></div>}
    {listings.isLoading ? <LoadingState label="Loading active produce listings…" /> : listings.isError ? <ErrorState message={errorMessage(listings.error)} retry={() => void listings.refetch()} /> : viewItems.length ? <div className="listing-grid">{viewItems.map((listing, index) => <ListingCard key={recordId(listing)} listing={listing} index={index} sellerView={sellerView} />)}</div> : <EmptyState title={sellerView ? "No active listings found" : "No matching produce right now"} description={sellerView ? "Your seller card is shown for listings you create. Add a listing from a saved harvest." : "Try another crop search or check back later. Listings are shown only when farmers create them."} action={sellerView ? <Link className="button button-primary" href={farmerPath("listings/new")}><Plus size={16} /> Create a listing</Link> : <Button variant="secondary" onClick={() => { setQuery(""); setCrop(""); }}>Clear search</Button>} />}
    <div className="market-privacy-note"><ShieldCheck size={15} /><span>FarmSaathi shares only approximate seller location in public listing views.</span><Badge kind="neutral">No payments are processed here</Badge></div>
  </PageSurface>;
}
function ListingCard({ listing, index, sellerView = false }: { listing: Listing; index: number; sellerView?: boolean }) {
  const role = sellerView ? "farmer" : "buyer";
  const seller = listing.seller as Record<string, unknown> | undefined;
  const loc = listing.location as Record<string, unknown> | undefined;
  const place = [loc?.village || loc?.city, loc?.district || loc?.state].filter(Boolean).join(", ");
  const hasImage = Boolean((listing as any).image_upload_id);
  return <Link href={`/${role}/market/${recordId(listing)}`} className={`listing-card listing-card-${index % 4}`}><div className="listing-art">{hasImage ? <img src={api.support.imageUrl(String((listing as any).image_upload_id))} alt={listing.crop_name} style={{ width: "100%", height: "100%", objectFit: "cover" }} /> : <div className="listing-pattern"><div className="listing-orbit" /><div className="listing-leaf"><Sprout size={34} strokeWidth={1.2} /></div></div>}<Badge kind={listing.status === "active" ? "success" : "neutral"}>{pretty(listing.status)}</Badge><span className="listing-grade">{listing.quality_grade ? pretty(listing.quality_grade) : "Grade not set"}</span></div><div className="listing-body"><div className="listing-headline"><div><div className="eyebrow">FARMER LISTING</div><h3>{listing.crop_name}</h3></div><span className="listing-price">{formatPrice(listing.currency, listing.price_per_unit)}<small>/ {listing.unit}</small></span></div><p className="listing-variety">{String(listing.variety || "Variety not recorded")} · {listing.remaining_quantity} {listing.unit} available</p><div className="listing-details"><span><MapPin size={14} /> {seller?.full_name ? String(seller.full_name) : sellerView ? "Your farm" : place || "Location not shared"}</span><span><Clock3 size={14} /> Until {dateText(listing.available_until)}</span></div><div className="listing-bottom"><span>{seller?.full_name && !sellerView ? `${String(seller.full_name)}${place ? ` · ${place}` : ""}` : place || "Location details private"}</span><span className="listing-link">{sellerView ? "Manage listing" : "View listing"} <ArrowRight size={14} /></span></div></div></Link>;
}

export function ListingDetailPage({ listingId }: { listingId: string }) {
  const { role } = useAuth(); const qc = useQueryClient(); const [, setLocation] = useLocation();
  const listing = useQuery({ queryKey: qk.listing(listingId), queryFn: () => api.marketplace.listing(listingId) });
  const [quantity, setQuantity] = useState(""); const [message, setMessage] = useState("");
  const interest = useMutation({ mutationFn: () => api.marketplace.interest(listingId, { quantity: Number(quantity), message: message.trim() || undefined }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: qk.listings }); await qc.invalidateQueries({ queryKey: ["records", "interests"] }); toast.success("Your interest was sent to the farmer."); setLocation("/buyer/interests"); }, onError: e => toast.error(errorMessage(e)) });
  const close = useMutation({ mutationFn: () => api.marketplace.closeListing(listingId), onSuccess: async () => { await qc.invalidateQueries({ queryKey: qk.listings }); toast.success("Listing closed and unreserved inventory released."); void listing.refetch(); }, onError: e => toast.error(errorMessage(e)) });
  if (listing.isLoading) return <PageSurface><LoadingState label="Loading listing details…" /></PageSurface>;
  if (listing.isError || !listing.data) return <PageSurface><ErrorState message="This listing could not be loaded." retry={() => void listing.refetch()} /></PageSurface>;
  const item = listing.data; const seller = item.seller as Record<string, unknown> | undefined; const location = item.location as Record<string, unknown> | undefined;
  const hasImage = Boolean((item as any).image_upload_id);
  return <PageSurface><Link href={`/${role}/market`} className="back-link"><ArrowLeft size={15} /> Market</Link><div className="listing-detail-layout"><div><div className={`listing-detail-art listing-card-${recordId(item).length % 4}`}>{hasImage ? <img src={api.support.imageUrl(String((item as any).image_upload_id))} alt={item.crop_name} style={{ width: "100%", height: "100%", objectFit: "cover", borderRadius: "12px" }} /> : <><div className="listing-orbit" /><Sprout size={72} strokeWidth={1.1} /></>}<Badge kind={item.status === "active" ? "success" : "neutral"}>{pretty(item.status)}</Badge></div><Card className="listing-info-card"><div className="eyebrow">AVAILABLE PRODUCE</div><h1>{item.crop_name}</h1><p className="listing-detail-variety">{String(item.variety || "Variety not recorded")} · {item.quality_grade ? `Grade ${item.quality_grade}` : "Grade not recorded"}</p><div className="listing-qty-price"><span><small>AVAILABLE QUANTITY</small><strong>{String(item.remaining_quantity)} {String(item.unit)}</strong></span><span><small>PRICE PER UNIT</small><strong>{formatPrice(item.currency, item.price_per_unit)}<small> / {String(item.unit)}</small></strong></span></div><div className="detail-key-grid"><span>Available from<strong>{dateText(item.available_from)}</strong></span><span>Available until<strong>{dateText(item.available_until)}</strong></span></div>{Boolean(item.description) && <p className="record-notes">{String(item.description)}</p>}</Card></div>
    <aside className="listing-action-stack"><Card className="seller-card"><div className="seller-avatar"><Sprout size={20} /></div><div><span className="eyebrow">GROWER</span><h3>{seller?.full_name ? String(seller.full_name) : "Farm listing"}</h3><p><MapPin size={13} /> {[location?.village || location?.city, location?.district || location?.state].filter(Boolean).join(", ") || "Approximate location only"}</p></div><div className="privacy-line"><ShieldCheck size={14} /> Exact farm location is private.</div></Card>
      {role === "buyer" ? <Card className="interest-form-card"><div className="eyebrow">BUYER INTEREST</div><h3>Start a conversation.</h3><p>Request a quantity; the farmer will review it. No payment is collected.</p><TextInput label={`Quantity (${item.unit})`} id="interest-quantity" type="number" min="0.01" max={item.remaining_quantity} step="0.1" required placeholder="e.g. 40" value={quantity} onChange={e => setQuantity(e.target.value)} /><TextArea label="Message to the farmer" id="interest-message" rows={3} placeholder="Optional message or delivery question" value={message} onChange={e => setMessage(e.target.value)} /><Button className="full-button" disabled={!quantity || Number(quantity) > Number(item.remaining_quantity) || interest.isPending || item.status !== "active"} onClick={() => interest.mutate()}>{interest.isPending ? "Sending…" : "Send interest"}<ArrowRight size={16} /></Button><small className="form-note">The farmer must accept your request before you can create a transaction.</small></Card> : <Card className="interest-form-card"><div className="eyebrow">YOUR LISTING</div><h3>Manage availability.</h3><p>Closing releases any unreserved quantity back to the harvest inventory.</p><Button variant="secondary" className="full-button" disabled={close.isPending || item.status !== "active"} onClick={() => { if (confirm("Close this produce listing? This releases only unreserved quantity.")) close.mutate(); }}>{close.isPending ? "Closing…" : "Close listing"}<X size={16} /></Button><small className="form-note">A listing with reserved transactions cannot be closed until those are completed or cancelled.</small></Card>}
    </aside></div>
  </PageSurface>;
}

export function ListingCreatePage() {
  const [, setLocation] = useLocation(); const qc = useQueryClient();
  const harvests = useQuery({ queryKey: ["records", "harvests"], queryFn: () => api.records.harvests({ limit: 100, offset: 0 }) });
  const crops = useQuery({ queryKey: qk.crops, queryFn: () => api.crops.list({ limit: 100, offset: 0 }) });
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState("");
  const [uploadId, setUploadId] = useState("");
  const [uploading, setUploading] = useState(false);
  const create = useMutation({ mutationFn: (payload: Record<string, unknown>) => api.marketplace.createListing(payload), onSuccess: async result => { await qc.invalidateQueries({ queryKey: qk.listings }); await qc.invalidateQueries({ queryKey: ["records", "harvests"] }); toast.success("Produce listing published."); setLocation(`/farmer/market/${recordId(result)}`); }, onError: e => toast.error(errorMessage(e)) });
  const [selectedHarvest, setSelectedHarvest] = useState(""); const chosen = harvests.data?.items.find(item => recordId(item) === selectedHarvest); const crop = crops.data?.items.find(item => recordId(item) === String(chosen?.crop_id || ""));
  async function choosePhoto(candidate?: File) {
    if (!candidate) return;
    if (!/^image\/(jpeg|png|webp)$/.test(candidate.type)) { toast.error("Choose a JPEG, PNG or WebP image."); return; }
    if (candidate.size > 8 * 1024 * 1024) { toast.error("Choose an image smaller than 8 MB."); return; }
    setFile(candidate); setPreview(URL.createObjectURL(candidate)); setUploadId(""); setUploading(true);
    try {
      const uploaded = await api.support.upload(candidate);
      setUploadId(uploaded.upload_id);
      toast.success("Produce photo uploaded.");
    } catch (error) {
      setUploadId("");
      toast.error(errorMessage(error));
    } finally {
      setUploading(false);
    }
  }
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const fd = new FormData(event.currentTarget); const locName = String(fd.get("location") || "").trim(); const loc = locName ? { source: "manual", city: locName } : undefined;
    create.mutate({
      harvest_id: selectedHarvest,
      crop_name: String(crop?.crop_name || fd.get("crop_name") || "").trim(),
      variety: fd.get("variety") || undefined,
      quantity: Number(fd.get("quantity")),
      unit: fd.get("unit"),
      price_per_unit: Number(fd.get("price")),
      currency: "INR",
      quality_grade: fd.get("grade") || undefined,
      available_until: fd.get("available_until") ? new Date(String(fd.get("available_until"))).toISOString() : undefined,
      location: loc,
      description: fd.get("description") || undefined,
      image_upload_id: uploadId || undefined,
    });
  }
  const available = harvests.data?.items.filter(item => !item.status || item.status === "available" || item.remaining_quantity !== 0) || [];
  return <PageSurface><Link href="/farmer/sell" className="back-link"><ArrowLeft size={15} /> Your produce</Link><PageHeading eyebrow="NEW PRODUCE LISTING" title="Bring your harvest to market." subtitle="The backend checks the offered quantity against the selected harvest before saving." />
    {harvests.isLoading && <LoadingState label="Loading harvest records…" />}{harvests.isError && <ErrorState message="Harvest records could not be loaded." retry={() => void harvests.refetch()} />}
    {harvests.data && available.length === 0 ? <EmptyState title="Add a harvest record first" description="A listing must be backed by produce you have already harvested." action={<Link className="button button-primary" href="/farmer/harvests/new">Record a harvest <ArrowRight size={16} /></Link>} /> : <Card className="form-card"><form className="record-form" onSubmit={submit}><div className="form-grid"><SelectInput label="Harvest record" id="harvest-id" required value={selectedHarvest} onChange={e => setSelectedHarvest(e.target.value)} options={available.map(item => ({ value: recordId(item), label: `${String(crops.data?.items.find(c => recordId(c) === String(item.crop_id))?.crop_name || "Crop")} · ${item.quantity} ${item.unit} harvested on ${dateText(item.harvested_at)}` }))} /><div className="harvest-availability"><Package size={15} /><span>{chosen ? `Selected harvest: ${chosen.quantity} ${chosen.unit}. The API enforces remaining sellable inventory.` : "Select a recorded harvest."}</span></div><TextInput label="Crop name" id="listing-crop" name="crop_name" required defaultValue={String(crop?.crop_name || "")} readOnly /><TextInput label="Variety" id="listing-variety" name="variety" defaultValue={String(crop?.variety || "")} placeholder="Optional" /><TextInput label="Quantity to offer" id="listing-quantity" name="quantity" type="number" min="0.01" step="0.1" max={chosen?.quantity} required placeholder="Enter amount" /><SelectInput label="Quantity unit" id="listing-unit" name="unit" defaultValue={String(chosen?.unit || "kg")} options={[{ value: "kg", label: "Kilograms" }, { value: "quintal", label: "Quintals" }, { value: "tonne", label: "Tonnes" }, { value: "piece", label: "Pieces" }]} /><TextInput label="Price per unit (INR)" id="listing-price" name="price" type="number" min="0.01" step="0.01" required placeholder="e.g. 32" /><SelectInput label="Quality grade" id="listing-grade" name="grade" options={[{ value: "premium", label: "Premium" }, { value: "A", label: "Grade A" }, { value: "B", label: "Grade B" }, { value: "standard", label: "Standard" }, { value: "ungraded", label: "Not graded" }]} /><TextInput label="Available until" id="listing-expiry" name="available_until" type="date" /><TextInput label="Approximate town or area" id="listing-location" name="location" placeholder="Optional; exact coordinates are not shared" /></div>
      <div className="upload-area" style={{ margin: "16px 0" }}>
        <input id="listing-produce-image" className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={event => void choosePhoto(event.target.files?.[0])} />
        <label htmlFor="listing-produce-image" className={`upload-pick ${uploading ? "is-uploading" : ""}`}>
          {uploading ? <LoaderCircle className="spin" size={21} /> : file ? <FileImage size={21} /> : <Upload size={21} />}
          <strong>{uploading ? "Uploading produce image…" : file ? file.name : "Upload your produce photo"}</strong>
          <span>Real harvest photo for buyers · JPEG, PNG or WebP up to 8 MB</span>
          <span className="button button-secondary">Choose photo</span>
        </label>
        {preview && <div className="image-preview"><img src={preview} alt="Listing preview" />{uploadId && <Badge kind="success">Uploaded</Badge>}<button type="button" className="icon-button" aria-label="Remove image" onClick={() => { setFile(null); setPreview(""); setUploadId(""); }}><X size={15} /></button></div>}
      </div>
      <TextArea label="Listing description" id="listing-description" name="description" rows={3} placeholder="Harvest freshness, packing or pickup details" /><div className="form-actions"><Link href="/farmer/sell" className="button button-ghost">Cancel</Link><Button type="submit" disabled={create.isPending || uploading || !selectedHarvest}>{create.isPending ? "Publishing…" : "Publish listing"}<ArrowRight size={16} /></Button></div></form></Card>}
  </PageSurface>;
}

export function InterestListPage({ sellerSide = false }: { sellerSide?: boolean }) {
  const { role } = useAuth(); const qc = useQueryClient(); const query = useQuery({ queryKey: ["records", "interests", sellerSide], queryFn: () => api.marketplace.interests({ limit: 50, offset: 0, side: sellerSide ? "farmer" : "buyer" }) });
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => api.marketplace.updateInterest(id, { status }), onSuccess: async (_, variables) => { await qc.invalidateQueries({ queryKey: ["records", "interests"] }); await qc.invalidateQueries({ queryKey: ["dashboard"] }); toast.success(variables.status === "accepted" ? "Buyer interest accepted." : "Interest updated."); }, onError: e => toast.error(errorMessage(e)) });
  const createTx = useMutation({ mutationFn: ({ listing_id, quantity, price }: { listing_id: string; quantity: number; price: number }) => api.marketplace.createTransaction({ listing_id, quantity, agreed_price_per_unit: price, currency: "INR" }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: qk.transactions }); await qc.invalidateQueries({ queryKey: ["records", "interests"] }); toast.success("Transaction created. No payment was taken."); }, onError: e => toast.error(errorMessage(e)) });
  const page = query.data;
  return <PageSurface><PageHeading eyebrow={sellerSide ? "BUYER INTEREST" : "YOUR REQUESTS"} title={sellerSide ? "Interest in your produce." : "Interest & replies."} subtitle={sellerSide ? "Review buyer requests. Accept or decline each request before any transaction can be created." : "Track your requests to farmers. An accepted request is still not a confirmed purchase."} />
    {query.isLoading ? <LoadingState label="Loading interest records…" /> : query.isError ? <ErrorState message="Interest records could not be loaded." retry={() => void query.refetch()} /> : page?.items.length ? <div className="interest-list">{page.items.map((interest, index) => <InterestCard key={recordId(interest) || index} interest={interest} sellerSide={sellerSide} pending={update.isPending || createTx.isPending} onUpdate={status => update.mutate({ id: recordId(interest), status })} onTransaction={() => createTx.mutate({ listing_id: String(interest.listing_id), quantity: Number(interest.requested_quantity), price: Number(interest.agreed_price_per_unit || interest.price_per_unit || 0) })} />)}</div> : <EmptyState title="No interest requests yet" description={sellerSide ? "When a buyer requests produce from one of your active listings, their request will appear here." : "Your requests to farmers will appear here with their response status."} action={<Link className="button button-secondary" href={sellerSide ? "/farmer/sell" : "/buyer/market"}>{sellerSide ? "View your listings" : "Browse the market"}<ArrowRight size={15} /></Link>} />}
  </PageSurface>;
}
function InterestCard({ interest, sellerSide, pending, onUpdate, onTransaction }: { interest: IdRecord; sellerSide: boolean; pending: boolean; onUpdate: (status: "accepted" | "rejected" | "cancelled") => void; onTransaction: () => void }) {
  const status = String(interest.status || "pending"); const buyer = interest.buyer as Record<string, unknown> | undefined;
  return <Card className="interest-card"><div className="interest-card-icon"><Sprout size={18} /></div><div className="interest-card-main"><div className="interest-card-title"><strong>{sellerSide ? String(buyer?.business_name || buyer?.full_name || "Buyer request") : String(interest.crop_name || "Produce request")}</strong><Badge kind={status === "accepted" ? "success" : status === "pending" ? "warning" : "neutral"}>{pretty(status)}</Badge></div><p>{String(interest.requested_quantity)} units requested · {dateText(interest.created_at)}</p><div className="interest-extra">{sellerSide ? `Buyer type: ${pretty(buyer?.buyer_type || "not recorded")}` : String(interest.message || "No message included.")}</div></div><div className="interest-actions">{sellerSide && status === "pending" && <><Button variant="secondary" disabled={pending} onClick={() => onUpdate("rejected")}><X size={14} /> Decline</Button><Button disabled={pending} onClick={() => onUpdate("accepted")}><Check size={14} /> Accept</Button></>}{!sellerSide && status === "pending" && <Button variant="ghost" disabled={pending} onClick={() => onUpdate("cancelled")}>Cancel request</Button>}{!sellerSide && status === "accepted" && <Button disabled={pending} onClick={onTransaction}>Create transaction <ArrowRight size={15} /></Button>}</div></Card>;
}

export function RequirementPage({ createMode = false }: { createMode?: boolean }) {
  const qc = useQueryClient(); const [, setLocation] = useLocation(); const requirements = useQuery({ queryKey: ["requirements"], queryFn: () => api.marketplace.requirements({ limit: 50, offset: 0 }), enabled: !createMode });
  const mutation = useMutation({ mutationFn: (payload: Record<string, unknown>) => api.marketplace.createRequirement(payload), onSuccess: async result => { await qc.invalidateQueries({ queryKey: ["requirements"] }); toast.success("Sourcing requirement posted."); setLocation(`/buyer/requirements/${recordId(result)}/matches`); }, onError: e => toast.error(errorMessage(e)) });
  if (createMode) return <RequirementCreate mutation={mutation} />;
  return <PageSurface><PageHeading eyebrow="BUYER SOURCING" title="A clear list of what you need." subtitle="Each requirement can be matched against currently active grower listings." action={<Link href="/buyer/requirements/new" className="button button-primary"><Plus size={16} /> Add requirement</Link>} />{requirements.isLoading ? <LoadingState /> : requirements.isError ? <ErrorState message={errorMessage(requirements.error)} retry={() => void requirements.refetch()} /> : requirements.data?.items.length ? <div className="requirement-grid">{requirements.data.items.map((req, i) => <RequirementCard key={recordId(req)} requirement={req} index={i} />)}</div> : <EmptyState title="No sourcing requirements" description="Post a crop, quantity and optional price or quality preference to compare available listings." action={<Link href="/buyer/requirements/new" className="button button-primary"><Plus size={16} /> Post a requirement</Link>} />}</PageSurface>;
}
function RequirementCreate({ mutation }: { mutation: ReturnType<typeof useMutation<IdRecord, Error, Record<string, unknown>>> }) {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fd = new FormData(event.currentTarget); mutation.mutate({ crop_name: String(fd.get("crop_name") || "").trim(), quantity_min: Number(fd.get("quantity_min")), ...(fd.get("quantity_max") ? { quantity_max: Number(fd.get("quantity_max")) } : {}), unit: fd.get("unit"), ...(fd.get("target_price") ? { target_price: Number(fd.get("target_price")) } : {}), currency: "INR", quality_grade: fd.get("quality_grade") || undefined, ...(fd.get("distance") ? { max_distance_km: Number(fd.get("distance")) } : {}), needed_by: fd.get("needed_by") ? new Date(String(fd.get("needed_by"))).toISOString() : undefined, location: fd.get("location") ? { source: "manual", city: fd.get("location") } : undefined, notes: fd.get("notes") || undefined }); }
  return <PageSurface><Link href="/buyer/requirements" className="back-link"><ArrowLeft size={15} /> Requirements</Link><PageHeading eyebrow="NEW SOURCING REQUIREMENT" title="Share what you're looking for." subtitle="The match list compares saved requirements with active listings. A match is informational, not a guarantee." /><Card className="form-card"><form className="record-form" onSubmit={submit}><div className="form-grid"><TextInput label="Crop name" id="req-crop" name="crop_name" required placeholder="e.g. Tomato" /><TextInput label="Minimum quantity" id="req-min" name="quantity_min" type="number" min="0.01" step="0.1" required placeholder="e.g. 100" /><TextInput label="Maximum quantity (optional)" id="req-max" name="quantity_max" type="number" min="0.01" step="0.1" placeholder="Optional" /><SelectInput label="Unit" id="req-unit" name="unit" defaultValue="kg" options={[{ value: "kg", label: "Kilograms" }, { value: "quintal", label: "Quintals" }, { value: "tonne", label: "Tonnes" }, { value: "piece", label: "Pieces" }]} /><TextInput label="Target price per unit (INR)" id="req-price" name="target_price" type="number" min="0.01" step="0.01" placeholder="Optional" /><SelectInput label="Preferred quality" id="req-grade" name="quality_grade" options={[{ value: "premium", label: "Premium" }, { value: "A", label: "Grade A" }, { value: "B", label: "Grade B" }, { value: "standard", label: "Standard" }]} /><TextInput label="Maximum distance (km)" id="req-distance" name="distance" type="number" min="1" max="1000" placeholder="Optional" /><TextInput label="Needed by" id="req-date" name="needed_by" type="date" /><TextInput label="Approximate town or district" id="req-location" name="location" placeholder="Optional" /></div><TextArea label="Notes for growers" id="req-notes" name="notes" rows={3} placeholder="Optional sourcing details" /><div className="form-actions"><Link href="/buyer/requirements" className="button button-ghost">Cancel</Link><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? "Posting…" : "Post requirement"}<ArrowRight size={16} /></Button></div></form></Card></PageSurface>;
}
function RequirementCard({ requirement, index }: { requirement: IdRecord; index: number }) { const role = "buyer"; return <Card className={`requirement-card req-tone-${index % 3}`}><div className="requirement-card-top"><span className="requirement-icon"><Sprout size={18} /></span><Badge kind={requirement.status === "active" ? "success" : "neutral"}>{pretty(requirement.status || "active")}</Badge></div><h3>{String(requirement.crop_name || "Crop")}</h3><p>{String(requirement.quantity_min || requirement.quantity || "—")}–{String(requirement.quantity_max || "open")} {String(requirement.unit || "kg")}</p><div className="requirement-meta"><span>Target price<strong>{requirement.target_price ? formatPrice(requirement.currency, requirement.target_price) : "Not set"}</strong></span><span>Quality<strong>{pretty(requirement.quality_grade || "Any")}</strong></span></div><Link href={`/${role}/requirements/${recordId(requirement)}/matches`} className="button button-secondary full-button">See potential matches <ArrowRight size={14} /></Link></Card>; }

export function MatchesPage({ requirementId }: { requirementId?: string }) {
  const query = useQuery({ queryKey: ["matches", requirementId || "all"], queryFn: () => api.marketplace.matches(requirementId) });
  const [busyListing, setBusyListing] = useState("");
  const buyer = useAuth().role === "buyer"; const qc = useQueryClient();
  const interested = useMutation({ mutationFn: ({ id, quantity }: { id: string; quantity: number }) => api.marketplace.interest(id, { quantity }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["records", "interests"] }); toast.success("Interest sent. The farmer will review your request."); }, onError: e => toast.error(errorMessage(e)), onSettled: () => setBusyListing("") });
  const items = query.data?.items || [];
  return <PageSurface><Link href="/buyer/requirements" className="back-link"><ArrowLeft size={15} /> Requirements</Link><PageHeading eyebrow="MATCHING" title="Compare live listings." subtitle="The backend compares crop, quantity, price, quality and approximate distance. Matches are not guaranteed." />
    {query.isLoading ? <LoadingState label="Comparing your requirement with live listings…" /> : query.isError ? <ErrorState message={errorMessage(query.error)} retry={() => void query.refetch()} /> : items.length ? <div className="matches-groups">{items.map((group, index) => <Card key={recordId(group.requirement) || index} className="match-group"><div className="match-group-heading"><div><span className="eyebrow">REQUIREMENT</span><h2>{String(group.requirement.crop_name || "Crop")}</h2><p>{String(group.requirement.quantity_min || group.requirement.quantity || "—")}–{String(group.requirement.quantity_max || "open")} {String(group.requirement.unit || "kg")}</p></div><Badge kind={group.match_status === "matches_found" ? "success" : "neutral"}>{group.matches.length} possible {group.matches.length === 1 ? "listing" : "listings"}</Badge></div>{group.matches.length ? <div className="match-cards">{group.matches.map((match, mIndex) => { const item = match.listing as Listing; const id = recordId(item); return <div className="match-item" key={id || mIndex}><div className={`crop-monogram crop-color-${mIndex % 4}`}><Sprout size={18} /></div><div className="match-item-main"><strong>{String(item.crop_name || "Produce")}</strong><span>{item.remaining_quantity} {item.unit} · {formatPrice(item.currency, item.price_per_unit)} / {item.unit}</span><div className="match-signals">{[match.quantity_range_match ? "Quantity" : "Quantity differs", match.price_within_target ? "Price" : "Price differs", match.quality_grade_match ? "Quality" : "Grade differs"].map((v, i) => <span key={i} className={v.includes("differs") ? "signal-off" : "signal-on"}>{v}</span>)}</div></div><div className="match-item-action"><Badge kind={match.match_type === "exact" ? "success" : "warning"}>{pretty(match.match_type)}</Badge>{buyer && <Button variant="secondary" disabled={interested.isPending || busyListing === id} onClick={() => { setBusyListing(id); interested.mutate({ id, quantity: Number(group.requirement.quantity_min || group.requirement.quantity || 1) }); }}>Express interest</Button>}</div></div>; })}</div> : <EmptyState title="No listings match this crop name yet" description="Matches refresh from current listing records. You can browse the market while you wait." action={<Link className="button button-secondary" href="/buyer/market">Browse listings <ArrowRight size={15} /></Link>} />}<div className="match-disclaimer"><span>i</span>Approximate distance may be unverified when either party did not provide coordinates. This is not an assurance of supply or delivery.</div></Card>)}</div> : <EmptyState title="No active sourcing requirements" description="Add a requirement first to compare it against current marketplace listings." action={<Link className="button button-primary" href="/buyer/requirements/new"><Plus size={16} /> Post a requirement</Link>} />}
  </PageSurface>;
}

export function TransactionsPage() {
  const { role } = useAuth(); const qc = useQueryClient(); const query = useQuery({ queryKey: qk.transactions, queryFn: () => api.marketplace.transactions({ limit: 50, offset: 0 }) });
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => api.marketplace.updateTransaction(id, { status }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: qk.transactions }); await qc.invalidateQueries({ queryKey: ["records", "interests"] }); await qc.invalidateQueries({ queryKey: ["dashboard"] }); toast.success("Transaction status updated. No payment was processed."); }, onError: e => toast.error(errorMessage(e)) });
  return <PageSurface><PageHeading eyebrow="MARKETPLACE RECORDS" title="Transactions, clearly tracked." subtitle="These are fulfillment records only. FarmSaathi does not take payments or provide escrow." />{query.isLoading ? <LoadingState label="Loading transactions…" /> : query.isError ? <ErrorState message={errorMessage(query.error)} retry={() => void query.refetch()} /> : query.data?.items.length ? <div className="transaction-list">{query.data.items.map((tx, index) => { const status = String(tx.status || "created"); const total = Number(tx.total_amount || Number(tx.quantity || 0) * Number(tx.agreed_price_per_unit || 0)); return <Card key={recordId(tx) || index} className="transaction-card"><div className="transaction-card-top"><span className="transaction-id">TX · {recordId(tx).slice(-8).toUpperCase()}</span><Badge kind={status === "completed" ? "success" : status === "cancelled" ? "neutral" : "warning"}>{pretty(status)}</Badge></div><div className="transaction-body"><div className="transaction-product"><span className={`crop-monogram crop-color-${index % 4}`}><Package size={17} /></span><div><strong>{String(tx.crop_name || "Produce")}</strong><span>{String(tx.quantity || "—")} {String(tx.unit || "kg")} · {dateText(tx.created_at)}</span></div></div><div className="transaction-total"><small>AGREED TOTAL</small><strong>{formatPrice(tx.currency, total)}</strong><span>{formatPrice(tx.currency, tx.agreed_price_per_unit)} per unit</span></div></div><div className="transaction-footer"><span><Clock3 size={14} /> {status === "created" ? role === "farmer" ? "Waiting for seller confirmation" : "Waiting for farmer confirmation" : status === "confirmed" ? "Order confirmed — no payment taken" : status === "completed" ? "Buyer marked received" : "Transaction closed"}</span><div className="transaction-actions">{status === "created" && role === "farmer" && <Button disabled={update.isPending} onClick={() => update.mutate({ id: recordId(tx), status: "confirmed" })}><Check size={14} /> Confirm</Button>}{status === "confirmed" && role === "buyer" && <Button disabled={update.isPending} onClick={() => update.mutate({ id: recordId(tx), status: "completed" })}><Check size={14} /> Mark received</Button>}{["created", "confirmed"].includes(status) && <Button variant="ghost" disabled={update.isPending} onClick={() => { if (confirm("Cancel this transaction? The reserved quantity will be returned to the listing.")) update.mutate({ id: recordId(tx), status: "cancelled" }); }}><X size={14} /> Cancel</Button>}</div></div></Card>; })}</div> : <EmptyState title="No transaction records" description="Once a farmer accepts your interest and a buyer creates a transaction, both sides can track its status here." action={<Link href={role === "buyer" ? "/buyer/interests" : "/farmer/buyer-interests"} className="button button-secondary">View interests <ArrowRight size={15} /></Link>} />}</PageSurface>;
}
